
development:
  adapter: postgresql
  database: stack_clone_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: stack_clone_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: stack_clone_production
  pool: 5
  timeout: 5000
